### ISSUE TITLE
We couldn't find the code for the Biformer used for  object detection

### ISSUE THREAD

**Issue by dyyzsu** [rayleizhu/BiFormer#11]
Thank you very much for such a great work. But we couldn't find the code for the Biformer used for object detection.

There is no code for Biformer.py in this directory “/BiFormer/object_detection/mmdet/models/backbones/”.

We would be very grateful if you could provide this code.

Thank you very much！

**Comment by rayleizhu** [comment]
https://github.com/rayleizhu/BiFormer/blob/8c6f0f7d908e9842d6dd6d11ed87507948d934fc/object_detection/train.py#L1

https://github.com/rayleizhu/BiFormer/blob/8c6f0f7d908e9842d6dd6d11ed87507948d934fc/object_detection/models_mm/biformer_mm.py#L12

**Comment by dyyzsu** [comment]
I truly appreciate your helpful response! Thank you so much for taking the time to address my issue.
