### ISSUE TITLE
注意力机制

### ISSUE THREAD

**Issue by PQCgit** [rayleizhu/BiFormer#13]
你好！
https://github.com/z1069614715/objectdetection_script/blob/master/cv-attention/Biformer.py
这个仓库是作者从你的代码库摘抄你的代码过去，请问里面的Attention模块是不是多头注意力机制呢

**Comment by rayleizhu** [comment]
> 你好！ https://github.com/z1069614715/objectdetection_script/blob/master/cv-attention/Biformer.py 这个仓库是作者从你的代码库摘抄你的代码过去，请问里面的Attention模块是不是多头注意力机制呢

 是
