### ISSUE TITLE
load pth error

### ISSUE THREAD

**Issue by Zcj18762244970** [rayleizhu/BiFormer#14]
this url : https://matix.li/e36fe9fb086c      ,   502badgateway

**Comment by rayleizhu** [comment]
Can you tell me for which file you meet the problem, so I can repair it?

Anyway, you can find all shared files [here](https://1drv.ms/u/s!AkBbczdRlZvChGsXFqAA-PVnA-R8?e=IPlOCG)

**Comment by rayleizhu** [comment]
Broken links are repaired now.
