### ISSUE TITLE
can not access your model ckpt.

### ISSUE THREAD

**Issue by liuxianyi** [rayleizhu/BiFormer#15]
i want to download your biformer-s model, but i get issuses.
<img width="1050" alt="截屏2023-05-22 15 26 34" src="https://github.com/rayleizhu/BiFormer/assets/33951338/3e7a5ce2-5dad-4226-98cb-d267b0025a7a">

**Comment by rayleizhu** [comment]
It turns out that the matrix cdn generated links are not persistent. You may manually download the files from [onedrive](https://1drv.ms/u/s!AkBbczdRlZvChGsXFqAA-PVnA-R8?e=IPlOCG) first.

**Comment by liuxianyi** [comment]
the onedrive link also can not be accessed. it is continuously loading.

**Comment by rayleizhu** [comment]
> the onedrive link also can not be accessed. it is continuously loading.

Are you in Mainland, China? If yes, I think you need some scientific network proxy (梯子).

**Comment by liuxianyi** [comment]
好的，我将尝试一下，谢谢。

**Comment by rayleizhu** [comment]
你能试一试下面这个链接吗？在没有梯子和有梯子两种情况下？
https://api.onedrive.com/v1.0/shares/s!AkBbczdRlZvChHI_XPhoadjaNxtO/root/content

**Comment by liuxianyi** [comment]
这个链接可以下载，可以给我一个Biformer-S的model嘛？

**Comment by rayleizhu** [comment]
> 这个链接可以下载，可以给我一个Biformer-S的model嘛？

稍等，在更新。一个小时内会上传。

**Comment by liuxianyi** [comment]
> 稍等，在更新。一个小时内会上传。

感谢！

**Comment by rayleizhu** [comment]
Repaired.

**Comment by liuxianyi** [comment]
> Repaired.
OK，可以下载了，👍
