### ISSUE TITLE
I want to train on the local computer, how should I change the code, author please can you publish a local computer training code?   

### ISSUE THREAD

**Issue by xuguangyi1999** [rayleizhu/BiFormer#16]

**Comment by rayleizhu** [comment]
You may compare the two launch commands below to figure out what to do.

![image](https://github.com/rayleizhu/BiFormer/assets/19933627/c1121e84-143e-4204-b750-3cf03a66fde1)

`hydra_main.py` is just a wrapper of `main.py` to support hydra configuration system and slurm environments. You may read the code of `hydra_main.py` to figure out how it works if you want.

Maybe I will update the script later to make it have a consistent launch command for both local environment and slurm environment.

**Comment by xuguangyi1999** [comment]
This allows training on your local computer:

python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py \
  --data-path ./data/in1k \
  --output_dir ./run \
  --input-size 224 --batch-size 32 --dist-eval \
  --model biformer_small \

**Comment by xuguangyi1999** [comment]
This allows training on your local computer:

python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py \
  --data-path ./data/in1k \
  --output_dir ./run \
  --input-size 224 --batch-size 32 --dist-eval \
  --model biformer_small \
