### ISSUE TITLE
Diffirence in routing attention

### ISSUE THREAD

**Issue by jyq2066** [rayleizhu/BiFormer#19]
Hi Author,
BiFormer inspires me a lot, I am searching for the routing attention where the ops contains two. What is the main routing attention you proposed in your paper.
Thanks!

**Comment by rayleizhu** [comment]
Thanks for your interest. Short answer: the two implementations are equivalent and you can check the comments here:

https://github.com/rayleizhu/BiFormer/blob/1697bbbeafb8680524898f1dcaac10defd0604be/ops/bra_nchw.py#L23.

You can also find more information in README:

<img width="940" alt="screenshot" src="https://github.com/rayleizhu/BiFormer/assets/19933627/647c2c55-36d8-4ddf-88e9-df896a97b9cd">
