### ISSUE TITLE
Objection detect code

### ISSUE THREAD

**Issue by C-C-Y** [rayleizhu/BiFormer#2]
Hello, may I ask when the code for object detection will be released? I look forward to your response. Thank you.

**Comment by rayleizhu** [comment]
The  MM project series share the same backbone usage. Hence it is not difficult to transfer the [segmentation code](https://github.com/rayleizhu/BiFormer/tree/public_release/semantic_segmentation) to detection.

As you asked, I will arrange the release in two weeks.

**Comment by C-C-Y** [comment]
> The MM project series share the same backbone usage. Hence it is not difficult to transfer the [segmentation code](https://github.com/rayleizhu/BiFormer/tree/public_release/semantic_segmentation) to detection.
> 
> As you asked, I will arrange the release in two weeks.

Thank you very much.

**Comment by LMMMEng** [comment]
Thank you for your wonderful work! Could you please release the config file for the detection first?

**Comment by rayleizhu** [comment]
> Thank you for your wonderful work! Could you please release the config file for the detection first?

Maybe by next Friday. I cannot guarantee as there are many other things on my hand. But I'm sure the full detection code can be released in two weeks.

**Comment by Hiyao-yy** [comment]
> 

Thanks for sharing, looking forward to your target detection code！

**Comment by Hiyao-yy** [comment]
Thanks for sharing, looking forward to the full detection code！

**Comment by rayleizhu** [comment]
The object detection code has been released.

Note that you need to update the environment if you have done setup previously.

**Comment by LMMMEng** [comment]
Thanks for your effort, I wonder if norm eval can improve performance https://github.com/rayleizhu/BiFormer/blob/8c6f0f7d908e9842d6dd6d11ed87507948d934fc/object_detection/models_mm/biformer_mm.py#L30
Moreover, could you let me know what the bugs are on the normalization layer?

**Comment by rayleizhu** [comment]
> Thanks for your effort, I wonder if norm eval can improve performance
 
I did not remember how much it helps. You may have a try. If you have a conclusion, please tell me here. By the way, `norm_eval=True` is the default choice of mmdetetction:

https://github.com/rayleizhu/BiFormer/blob/8c6f0f7d908e9842d6dd6d11ed87507948d934fc/object_detection/configs/_base_/models/mask_rcnn_r50_fpn.py#L12


> Moreover, could you let me know what the bugs are on the normalization layer?

See my comments here:

https://github.com/rayleizhu/BiFormer/blob/8c6f0f7d908e9842d6dd6d11ed87507948d934fc/object_detection/models_mm/biformer_mm.py#L50

Actually, I do not know if it is this modification that works. There are some other differences (not in my model but functions or environment provided by third parties), as I mentioned in the [README](https://github.com/rayleizhu/BiFormer/tree/8c6f0f7d908e9842d6dd6d11ed87507948d934fc/object_detection#readme).

**Comment by LMMMEng** [comment]
> > Thanks for your effort, I wonder if norm eval can improve performance
> 
> I did not remember how much it helps. You may have a try. If you have a conclusion, please tell me here. By the way, `norm_eval=True` is the default choice of mmdetetction:
> 
> https://github.com/rayleizhu/BiFormer/blob/8c6f0f7d908e9842d6dd6d11ed87507948d934fc/object_detection/configs/_base_/models/mask_rcnn_r50_fpn.py#L12
> 
> > Moreover, could you let me know what the bugs are on the normalization layer?
> 
> See my comments here:
> 
> https://github.com/rayleizhu/BiFormer/blob/8c6f0f7d908e9842d6dd6d11ed87507948d934fc/object_detection/models_mm/biformer_mm.py#L50
> 
> Actually, I do not know if it is this modification that works. There are some other differences (not in my model but functions or environment provided by third parties), as I mentioned in the [README](https://github.com/rayleizhu/BiFormer/tree/8c6f0f7d908e9842d6dd6d11ed87507948d934fc/object_detection#readme).

Many thanks!
