### ISSUE TITLE
关于Bi-level Routing Attention的问题

### ISSUE THREAD

**Issue by Philharmy-Wang** [rayleizhu/BiFormer#29]
作者您好！最近拜读了您的论文，在目标检测网络上测试了本文提出的方法，效果非常好。
但我还有一些问题想咨询您一下。论文中的Bi-level Routing Attention，有没有具体的结构图？
如果方便的话，麻烦作者提供一下，万分感谢！

**Comment by rayleizhu** [comment]
论文里有一个这样的，不是你想要的吗？
![image](https://github.com/rayleizhu/BiFormer/assets/19933627/6625dcfe-2483-4ae6-9428-44c2ccabadd8)

画过一个计算图长这样，感觉有点复杂所以没有放到论文里
![image](https://github.com/rayleizhu/BiFormer/assets/19933627/6b5ea0cb-d8df-440e-a984-cec554877052)

图都是用[draw.io](https://app.diagrams.net/)画出来的

**Comment by Philharmy-Wang** [comment]
好的，非常感谢！
