### ISSUE TITLE
一个可能的BUG

### ISSUE THREAD

**Issue by ZhangIceNight** [rayleizhu/BiFormer#3]

**Comment by ZhangIceNight** [comment]
你好，我发现在新版本的nchw版本的代码中，rrsda.py 文件
```
if auto_pad and (q_pad_b > 0 or q_pad_r > 0):
        output = output[:, :, :-q_pad_b, :-q_pad_r]
```
如果 `q_pad_b` 和 `q_pad_r` 中只有一个不为零，那下面的表达式 就会出现 `[:,:,:-0,:-q_pad_r]` 这类情况

**Comment by ZhangIceNight** [comment]
我这样做了一点简单修改，目前可以正常运行了
```
if auto_pad and (q_pad_b > 0 or q_pad_r > 0):
        if q_pad_b == 0:
            output = output[:, :, :, :-q_pad_r]
        elif q_pad_r == 0:
            output = output[:, :, :-q_pad_b, :]
        else:
            output = output[:, :, :-q_pad_b, :-q_pad_r]
```

**Comment by rayleizhu** [comment]
> 我这样做了一点简单修改，目前可以正常运行了
> 
> ```
> if auto_pad and (q_pad_b > 0 or q_pad_r > 0):
>         if q_pad_b == 0:
>             output = output[:, :, :, :-q_pad_r]
>         elif q_pad_r == 0:
>             output = output[:, :, :-q_pad_b, :]
>         else:
>             output = output[:, :, :-q_pad_b, :-q_pad_r]
> ```

感谢指出，我会尽快修复这个问题。

**Comment by rayleizhu** [comment]
已修复
