### ISSUE TITLE
A question about local context enhancement (LCE).

### ISSUE THREAD

**Issue by stella-von** [rayleizhu/BiFormer#30]
May I ask how much improvement the LCE used in the article has brought?

**Comment by rayleizhu** [comment]
The short answer is, I do not know. I did not do this ablation experiment after the architecture is finalized.

LCE is added to our architecture during our early exploration period. If I remember correctly, At that time, we used DWConv in stages 1 & 2, BRA in stages 3 & 4, the improvement brought by LCE is 0.2 or so. I guess it plays the role of position encoding.

**Comment by stella-von** [comment]
Thanks.
