### ISSUE TITLE
from ops.bra_legacy import BiLevelRoutingAttention

### ISSUE THREAD

**Issue by zhangwenkuan** [rayleizhu/BiFormer#31]
Why is the following error reported after the ops library is installed:
ModuleNotFoundError: No module named 'ops.bra_legacy'

**Comment by rayleizhu** [comment]
What's the command you are executing? What is the working directory when you execute it?

You may also need some tutorials about [python's import mechanism](https://docs.python.org/3/reference/import.html)

**Comment by zhangwenkuan** [comment]
Hello, thank you for your answer, my problem has been solved!

**Comment by 20191844308** [comment]
你好，出现了同样的问题，请问怎么解决的

**Comment by zhangwenkuan** [comment]
仔细看代码，在另一个.py文件中有的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月15日(星期一) 下午5:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rayleizhu/BiFormer] from ops.bra_legacy import BiLevelRoutingAttention (Issue #31)














 
你好，出现了同样的问题，请问怎么解决的

**Comment by 20191844308** [comment]
对呀，明明代码里有，为什么导入还会报错
