### ISSUE TITLE
Environmental settings

### ISSUE THREAD

**Issue by lmqomo12** [rayleizhu/BiFormer#42]
could u please tell me what is the runtime environment required to run tbiformer for image classification tasks， bsc I don't see in the readme, such as torch python, etc，Looking forward to your reply soon

**Comment by rayleizhu** [comment]
https://github.com/rayleizhu/BiFormer/blob/public_release/INSTALL.md

https://github.com/rayleizhu/BiFormer/blob/public_release/environment.yaml

**Comment by lmqomo12** [comment]
thank u so much for your reply！it is helpful for me



---Original---
From: "ZHU ***@***.***&gt;
Date: Fri, Mar 8, 2024 11:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rayleizhu/BiFormer] Environmental settings (Issue #42)




 
https://github.com/rayleizhu/BiFormer/blob/public_release/INSTALL.md
 
https://github.com/rayleizhu/BiFormer/blob/public_release/environment.yaml
