### ISSUE TITLE
A question about interpretability

### ISSUE THREAD

**Issue by sxl845414442** [rayleizhu/BiFormer#7]
Hello author, I am a newcomer in this field. I would like to ask if your Biformer has interpretability and where it is reflected.

**Comment by rayleizhu** [comment]
Can your question be more concrete? I have no idea which interpretability you expect. If you have not read our paper yet, I would suggest you read it first.

**Comment by sxl845414442** [comment]
> Can your question be more concrete? I have no idea which interpretability you expect. If you have not read our paper yet, I would suggest you read it first.

Thank you for your answer. I would like to know how to visualize the predicted results into a heat map and how to implement the specific code.

**Comment by rayleizhu** [comment]
> I would like to know how to visualize the predicted results into a heat map 

(1) Get the routing indices and attention matrix. (2) Create a pseudo color map with extracted indices or attention matrix. (3) Alpha blending image and the pseudo color map.

The visualization demo is on my to-do list. But I'm busy recently, hence it may take months before the release. 

> and how to implement the specific code.

What do you mean by "specific code"? Which part of the code?

**Comment by sxl845414442** [comment]
> > 以及如何实现特定代码。
> 
> “特定代码”是什么意思？代码的哪一部分？

I thought the heat map was implemented by code, but I couldn't find which code to run.
