### ISSUE TITLE
Problems with using the biformer attention mechanism

### ISSUE THREAD

**Issue by Gaoang1** [rayleizhu/BiFormer#8]
RuntimeError: scatter_add_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's accepta...

**Comment by rayleizhu** [comment]
> RuntimeError: scatter_add_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's accepta...

I did not meet such errors in all of my experiments and hence can not provide suggestions. Did you change something?

**Comment by emm110112** [comment]
I am also having the same problem, may I ask what is the reason for this situation

**Comment by Gaoang1** [comment]
> 

I don't know what causes it, but you can fix it by setting torch.use_deterministic_algorithms(True) to False
